/******************************************************************************
 *                                  LICENSE                                   *
 ******************************************************************************
 *  This file is part of vrmit.                                               *
 *                                                                            *
 *  vrmit is free software: you can redistribute it and/or modify             *
 *  it under the terms of the GNU General Public License as published by      *
 *  the Free Software Foundation, either version 3 of the License, or         *
 *  (at your option) any later version.                                       *
 *                                                                            *
 *  vrmit is distributed in the hope that it will be useful,                  *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of            *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the             *
 *  GNU General Public License for more details.                              *
 *                                                                            *
 *  You should have received a copy of the GNU General Public License         *
 *  along with vrmit.  If not, see <https://www.gnu.org/licenses/>.           *
 ******************************************************************************
 *  Purpose:                                                                  *
 *      Provides the RK4 integrator and electromagnetic force.                *
 ******************************************************************************
 *  Author:     Ryan Maguire                                                  *
 *  Date:       June 19, 2025                                                 *
 ******************************************************************************/

/*  printf found here, used for printing the computation time.                */
#include <stdio.h>

/*  sqrt found here, used for the Coulomb force.                              */
#include <math.h>

/*  clock_t typedef and the clock function, used for timing the calculation.  */
#include <time.h>

/*  Function prototypes, and typedefs for force, Vec3, and Vec6.              */
#include "rk4.h"

/******************************************************************************
 *  Function:                                                                 *
 *      coulomb                                                               *
 *  Purpose:                                                                  *
 *      Computes the Coulomb force on a particle in the plane. It is assumed  *
 *      the force is generated by a point source at the origin, and that both *
 *      have positive unit charge. Units are made so that the Coulomb         *
 *      constant is 1 as well, k = 1.                                         *
 *  Arguments:                                                                *
 *      position (const Vec3 * const):                                        *
 *          The point in the plane where the second charge lies.              *
 *  Output:                                                                   *
 *      out (Vec3):                                                           *
 *          The force exterted on the point by the charge at the origin.      *
 ******************************************************************************/

Vec3 coulomb_f(const Vec3 * const pos, const Vec3 * const vel, const FieldObject * objects, size_t obj_size)
{    
    /*  Variable for the output force.                                        */
    Vec3 out = {0.0, 0.0, 0.0};

    for (size_t i = 0; i < obj_size; i++) 
    {
        if (objects[i].type == POINT_CHARGE) 
        {
            const double rsq = (pos->x - objects[i].p.x) * (pos->x - objects[i].p.x)
            + (pos->y - objects[i].p.y) * (pos->y - objects[i].p.y)
            + (pos->z - objects[i].p.z) * (pos->z - objects[i].p.z);

            /*  The L2 norm, given by Pythagoras, || P || = sqrt(x^2 + y^2).          */
            const double r = sqrt(rsq);

            /*  The input vector is not necessary a unit vector. The inverse square   *
            *  law thus becomes:                                                     *
            *                                                                        *
            *             ^          ->                                              *
            *             R          R                                               *
            *      F = -------- = --------                                           *
            *                 2          3                                           *
            *          || R ||    || R ||                                            *
            *                                                                        *
            *  Where the "hat" indicates the unit vector in the direction of R. The  *
            *  scale factor is hence the reciprocal of the cube of the norm.         */
            const double scale = objects[i].data.charge.q / (r * rsq);

            /*  The force is just the scale factor times the position vector. Compute.*/
            out.x += (pos->x - objects[i].p.x) * scale;
            out.y += (pos->y - objects[i].p.y) * scale;
            out.z += (pos->z - objects[i].p.z) * scale; 
        }
    }

    return out;
}
/*  End of coulomb.                                                           */

/*  B: Magnetic Field                                                         */
Vec3 bar_magnet_b(const Vec3 * const pos, const Vec3 * const vel, const FieldObject * objects, size_t obj_count) 
{
    /*  Variable for the output force.                                        */
    Vec3 out = {0.0, 0.0, 0.0};

    for (size_t i = 0; i < obj_count; i++) 
    {
        if (objects[i].type == BAR_MAGNET) 
        {
            const double rsq = (pos->x - objects[i].p.x) * (pos->x - objects[i].p.x)
            + (pos->y - objects[i].p.y) * (pos->y - objects[i].p.y)
            + (pos->z - objects[i].p.z) * (pos->z - objects[i].p.z);

            const double r = sqrt(rsq);

            const double scale = 1.0 / (r * rsq);

            const Vec3 r_hat = {
                (pos->x - objects[i].p.x) / r, 
                (pos->y - objects[i].p.y) / r,
                (pos->z - objects[i].p.z) / r};

            const double mdotr_hat = (objects[i].data.bar_magnet.m.x * r_hat.x) + 
            (objects[i].data.bar_magnet.m.y * r_hat.y) + 
            (objects[i].data.bar_magnet.m.z * r_hat.z);

            out.x += scale * (3 * (mdotr_hat) * r_hat.x - objects[i].data.bar_magnet.m.x);
            out.y += scale * (3 * (mdotr_hat) * r_hat.y - objects[i].data.bar_magnet.m.y);
            out.z += scale * (3 * (mdotr_hat) * r_hat.z - objects[i].data.bar_magnet.m.z);
        } 
    }

    return out;
}

/*  Bar Magnet Force w/ Corresponding Cross Product Calculation                       */
Vec3 bar_magnet_f(const Vec3 * const pos, const Vec3 * const vel, const FieldObject * objects, size_t obj_count) 
{
    const Vec3 B = bar_magnet_b(pos, NULL, objects, obj_count);
    Vec3 out = {vel->y * B.z - vel->z * B.y, 
        vel->z * B.x - vel->x * B.z, 
        vel->x * B.y - vel->y * B.x};
    return out;
}

/*  Net force to compute particle pos/vel with multiple types of electromagnetic phenomena.  */
Vec3 net_force(const Vec3 * const pos, const Vec3 * const vel, const FieldObject * objects, size_t obj_count) 
{
    Vec3 out = {0.0, 0.0, 0.0};

    Vec3 E_f = coulomb_f(pos, vel, objects, obj_count);
    Vec3 B_f = bar_magnet_f(pos, vel, objects, obj_count);

    out.x += E_f.x + B_f.x;
    out.y += E_f.y + B_f.y;
    out.z += E_f.z + B_f.z;

    return out;
}

/* Net E & B Fields to compute field lines (WIP FEATURE)                                      */
Vec3 net_e_field(const Vec3 * const pos, const FieldObject * objects, size_t obj_count) 
{
    Vec3 E_coulomb = coulomb_f(pos, NULL, objects, obj_count); // particle q = 1, should make a seperate coulomb_e function
    return E_coulomb;
}

Vec3 net_e_field_norm(const Vec3 * const pos, const FieldObject * objects, size_t obj_count) 
{
    Vec3 out = {0.0, 0.0, 0.0};
    Vec3 E = net_e_field(pos, objects, obj_count);

    float E_sq = E.x * E.x + E.y * E.y + E.z * E.z;
    float E_mag = sqrt(E_sq);

    out.x = E.x / E_mag;
    out.y = E.y / E_mag;
    out.z = E.z / E_mag;

    return out;
}

Vec3 net_b_field(const Vec3 * const pos, const FieldObject * objects, size_t obj_count) 
{
    Vec3 B_bar_magnet = bar_magnet_b(pos, NULL, objects, obj_count);
    return B_bar_magnet;
}

Vec3 net_b_field_norm(const Vec3 * const pos, const FieldObject * objects, size_t obj_count) 
{
    Vec3 out = {0.0, 0.0, 0.0};
    Vec3 B = net_b_field(pos, objects, obj_count);

    float B_sq = B.x * B.x + B.y * B.y + B.z * B.z;
    float B_mag = sqrt(B_sq);

    out.x = B.x / B_mag;
    out.y = B.y / B_mag;
    out.z = B.z / B_mag;

    return out;
}

/******************************************************************************
 *  Function:                                                                 *
 *      rk4_factor                                                            *
 *  Purpose:                                                                  *
 *      Computes the perturbation factors for the phase-space version of RK4. *
 *      The increment in RK4 is given by a linear combination of 4 points in  *
 *      phase space, each of which has a similar formula. This function       *
 *      calculates the locations of these points.                             *
 *  Arguments:                                                                *
 *      u0 (const Vec6 * const):                                              *
 *          The current location of the point for the ODE.                    *
 *      h (double):                                                           *
 *          The step size used in RK4.                                        *
 *      u1 (const Vec6 * const):                                              *
 *          The perturbation point, these are the k_n's in the RK4 method.    *
 *      f (force):                                                            *
 *          The force on the particle. We use Newton's 2nd law and apply RK4  *
 *          to find the path of the particle.                                 *
 *  Output:                                                                   *
 *      out (Vec4):                                                           *
 *          The new perturbation factor, one of the k_n terms.                *
 ******************************************************************************/
Vec6 rk4_factor(const Vec6 * const u0, double h, const Vec6 * const u1, force f, const FieldObject * objects, size_t obj_count)
{
    /*  Declare a variable for the output.                                    */
    Vec6 out;

    /*  Place holder for the Euler-like step used to compute out.p and out.v. */
    Vec3 p;

    /*  u1 acts like the velocity in phase-space, and u0 is the position.     *
     *  Calculate the new point by applying Euler's method.                   */
    p.x = u0->p.x + h * u1->p.x;
    p.y = u0->p.y + h * u1->p.y;
    p.z = u0->p.z + h * u1->p.z;

    /*  Same idea, but for the velocity component in phase-space. Here, u1    *
     *  acts as acceleration, and u0 acts as velocity. Update.                */
    out.p.x = u0->v.x + h * u1->v.x;
    out.p.y = u0->v.y + h * u1->v.y;
    out.p.z = u0->v.z + h * u1->v.z;

    /*  The new velocity is given by the force at the current point. Compute. */
    out.v = f(&p, &out.p, objects, obj_count);

    return out;
}

Vec3 rk4_factor_field(const Vec3 * const u0, double h, const Vec3 * const u1, field f, const FieldObject * objects, size_t obj_count) 
{
        /*  Declare a variable for the output.                                */
    Vec3 out;

    /*  Place holder for the Euler-like step used to compute out.p and out.v. */
    Vec3 p;

    /*  u1 acts like the velocity in phase-space, and u0 is the position.     *
     *  Calculate the new point by applying Euler's method.                   */
    p.x = u0->x + h * u1->x;
    p.y = u0->y + h * u1->y;
    p.z = u0->z + h * u1->z;

    /*  The new velocity is given by the force at the current point. Compute. */
    out = f(&p, objects, obj_count);

    return out;
}
/*  End of rk4_factor.                                                        */

/******************************************************************************
 *  Function:                                                                 *
 *      rk4                                                                   *
 *  Purpose:                                                                  *
 *      Performs RK4 to numerical solve an ODE.                               *
 *  Arguments:                                                                *
 *      f (force):                                                            *
 *          The force on the particle. We use Newton's 2nd law and apply RK4  *
 *          to find the path of the particle.                                 *
 *      u (Vec6 * const):                                                     *
 *          The initial position and velocity of the particle.                *
 *      h (double):                                                           *
 *          The step size.                                                    *
 *      steps (size_t):                                                       *
 *          The number of steps to perform.                                   *
 *  Output:                                                                   *
 *      None (void).                                                          *
 ******************************************************************************/
void rk4(force f, Vec6 * const u, double h, size_t steps, const FieldObject * objects, size_t obj_count)
{
    /*  Index for keeping track of the number of iterations performed.        */
    size_t n = 0;

    /*  Constant multiples of h used in the computation.                      */
    const double h0 = 0.5 * h;
    const double h1 = h * 0.1666666666666667;

    /*  Current acceleration vector given by the starting position.           */
    Vec3 a = f(&u->p, &u->v, objects, obj_count);

    /*  Compute the initial Runge-Kutta factors.                              */
    Vec6 k1 = {u->v, a};
    Vec6 k2 = rk4_factor(u, h0, &k1, f, objects, obj_count);
    Vec6 k3 = rk4_factor(u, h0, &k2, f, objects, obj_count);
    Vec6 k4 = rk4_factor(u, h, &k3, f, objects, obj_count);

    /*  Iteratively performed RK4.                                            */
    for (n = 0; n < steps; ++n)
    {
        /*  We numerically solve d^2/dt^2 p = F(p) in two steps. First we     *
         *  compute the velocity dp/dt, meaning we solve dv/dt = F(p). We     *
         *  solve numerically with the Runge-Kutta method. We use this v to   *
         *  compute p via dp/dt = v, solving numerically again. So long as dt *
         *  is small, the error should be small as well. Error is O(dt^4).    */
        u->p.x += h1 * (k1.p.x + 2.0*k2.p.x + 2.0*k3.p.x + k4.p.x);
        u->p.y += h1 * (k1.p.y + 2.0*k2.p.y + 2.0*k3.p.y + k4.p.y);
        u->p.z += h1 * (k1.p.z + 2.0*k2.p.z + 2.0*k3.p.z + k4.p.z);

        /*  Velocity component of the RK4 update.                             */
        u->v.x += h1 * (k1.v.x + 2.0*k2.v.x + 2.0*k3.v.x + k4.v.x);
        u->v.y += h1 * (k1.v.y + 2.0*k2.v.y + 2.0*k3.v.y + k4.v.y);
        u->v.z += h1 * (k1.v.z + 2.0*k2.v.z + 2.0*k3.v.z + k4.v.z);

        /*  Update the Runge-Kutta factors.                                   */
        a = f(&u->p, &u->v, objects, obj_count);

        k1.p = u->v;
        k1.v = a;

        k2 = rk4_factor(u, h0, &k1, f, objects, obj_count);
        k3 = rk4_factor(u, h0, &k2, f, objects, obj_count);
        k4 = rk4_factor(u, h, &k3, f, objects, obj_count);
    }
}

void rk4_field(field f, Vec3 * const p, double h, size_t steps, const FieldObject * objects, size_t obj_count) 
{
    /*  Index for keeping track of the number of iterations performed.        */
    size_t n = 0;

    /*  Constant multiples of h used in the computation.                      */
    const double h0 = 0.5 * h;
    const double h1 = h * 0.1666666666666667;

    /*  Compute the initial Runge-Kutta factors.                              */
    Vec3 k1 = f(p, objects, obj_count);
    Vec3 k2 = rk4_factor_field(p, h0, &k1, f, objects, obj_count);
    Vec3 k3 = rk4_factor_field(p, h0, &k2, f, objects, obj_count);
    Vec3 k4 = rk4_factor_field(p, h, &k3, f, objects, obj_count);
    
    /*  Iteratively performed RK4.                                            */
    for (n = 0; n < steps; ++n)
    {
        /*  We numerically solve d^2/dt^2 p = F(p) in two steps. First we     *
         *  compute the velocity dp/dt, meaning we solve dv/dt = F(p). We     *
         *  solve numerically with the Runge-Kutta method. We use this v to   *
         *  compute p via dp/dt = v, solving numerically again. So long as dt *
         *  is small, the error should be small as well. Error is O(dt^4).    */
        p->x += h1 * (k1.x + 2.0*k2.x + 2.0*k3.x + k4.x);
        p->y += h1 * (k1.y + 2.0*k2.y + 2.0*k3.y + k4.y);
        p->z += h1 * (k1.z + 2.0*k2.z + 2.0*k3.z + k4.z);

        /*  Update the Runge-Kutta factors.                                   */
        k1 = f(p, objects, obj_count);
        k2 = rk4_factor_field(p, h0, &k1, f, objects, obj_count);
        k3 = rk4_factor_field(p, h0, &k2, f, objects, obj_count);
        k4 = rk4_factor_field(p, h, &k3, f, objects, obj_count);
    }
}
/*  End of rk4.                                                               */

/******************************************************************************
 *  Function:                                                                 *
 *      integrate                                                             *
 *  Purpose:                                                                  *
 *      Given a set of data points, performs RK4 on all of them.              *
 *  Arguments:                                                                *
 *      f (force):                                                            *
 *          The force on the particle. We use Newton's 2nd law and apply RK4  *
 *          to find the path of the particle.                                 *
 *      u (Vec6 * const):                                                     *
 *          Array with the initial positions and velocities of the particles. *
 *      n_elements (size_t):                                                  *
 *          The number of elements in the "u" array.                          *
 *      h (double):                                                           *
 *          The step size.                                                    *
 *      steps (size_t):                                                       *
 *          The number of steps to perform.                                   *
 *  Output:                                                                   *
 *      None (void).                                                          *
 ******************************************************************************/
void
integrate(force f, Vec6 * const u, size_t n_elements, double h, size_t steps, const FieldObject * objects, size_t obj_count)
{
    /*  Variable for indexing over the array.                                 */
    size_t n;

    /*  Loop through each point and apply RK4.                                */
    for (n = 0; n < n_elements; ++n)
        rk4(f, &u[n], h, steps, objects, obj_count);

}
/*  End of integrate.                                                         */

void 
integrate_field(field f, Vec3 * const p, size_t n_elements, double h, size_t steps, const FieldObject * objects, size_t obj_count) 
{
    size_t n;

    for (n = 0; n < n_elements; ++n) 
    {
        rk4_field(f, &p[n], h, steps, objects, obj_count);
    }
}